const c = @import("pkcs11");

pub const Error = error{
    // PKCS#11 Errors
    Cancel,
    HostMemory,
    SlotIdInvalid,
    GeneralError,
    FunctionFailed,
    ArgumentsBad,
    NoEvent,
    NeedToCreateThreads,
    CantLock,
    AttributeReadOnly,
    AttributeSensitive,
    AttributeTypeInvalid,
    AttributeValueInvalid,
    ActionProhibited,
    DataInvalid,
    DataLenRange,
    DeviceError,
    DeviceMemory,
    DeviceRemoved,
    EncryptedDataInvalid,
    EncryptedDataLenRange,
    FunctionCancelled,
    FunctionNotParallel,
    FunctionNotSupported,
    KeyHandleInvalid,
    KeySizeRange,
    KeyTypeInconsistent,
    KeyNotNeeded,
    KeyChanged,
    KeyNeeded,
    KeyIndigestible,
    KeyFunctionNotPermitted,
    KeyNotWrappable,
    KeyUnextractable,
    MechanismInvalid,
    MechanismParamInvalid,
    ObjectHandleInvalid,
    OperationActive,
    OperationNotInitialized,
    PINIncorrect,
    PINInvalid,
    PINLenRange,
    PINExpired,
    PINLocked,
    SessionClosed,
    SessionCount,
    SessionHandleInvalid,
    SessionParallelNotSupported,
    SessionReadOnly,
    SessionExists,
    SessionReadOnlyExists,
    SessionReadWriteSOExists,
    SignatureInvalid,
    SignatureLenRange,
    TemplateIncomplete,
    TemplateInconsistent,
    TokenNotPresent,
    TokenNotRecognized,
    TokenWriteProhibited,
    UnwrappingKeyHandleInvalid,
    UnwrappingKeySizeRange,
    UnwrappingKeyTypeInconsistent,
    UserAlreadyLoggedIn,
    UserNotLoggedIn,
    UserPINNotInitialized,
    UserTypeInvalid,
    UserAnotherAlreadyLoggedIn,
    UserTooManyTypes,
    WrappedKeyInvalid,
    WrappedKeyLenRange,
    WrappingKeyHandleInvalid,
    WrappingKeySizeRange,
    WrappingKeyTypeInconsistent,
    RandomSeedNotSupported,
    RandomNoRNG,
    DomainParamsInvalid,
    CurveNotSupported,
    BufferTooSmall,
    SavedStateInvalid,
    InformationSensitive,
    StateUnsavable,
    CryptokiNotInitialized,
    CryptokiAlreadyInitialized,
    MutexBad,
    MutexNotLocked,
    NewPINMode,
    NextOTP,
    ExceededMaxIterations,
    FIPSSelfTestFailed,
    LibraryLoadFailed,
    PINTooWeak,
    PublicKeyInvalid,
    FunctionRejected,
    // Our own errors
    Unknown,
    OutOfMemory,
};

pub const ReturnValue = enum(c_ulong) {
    ok = c.CKR_OK,
    cancel = c.CKR_CANCEL,
    host_memory = c.CKR_HOST_MEMORY,
    slot_id_invalid = c.CKR_SLOT_ID_INVALID,
    general_error = c.CKR_GENERAL_ERROR,
    function_failed = c.CKR_FUNCTION_FAILED,
    arguments_bad = c.CKR_ARGUMENTS_BAD,
    no_event = c.CKR_NO_EVENT,
    need_to_create_threads = c.CKR_NEED_TO_CREATE_THREADS,
    cant_lock = c.CKR_CANT_LOCK,
    attribute_read_only = c.CKR_ATTRIBUTE_READ_ONLY,
    attribute_sensitive = c.CKR_ATTRIBUTE_SENSITIVE,
    attribute_type_invalid = c.CKR_ATTRIBUTE_TYPE_INVALID,
    attribute_value_invalid = c.CKR_ATTRIBUTE_VALUE_INVALID,
    action_prohibited = c.CKR_ACTION_PROHIBITED,
    data_invalid = c.CKR_DATA_INVALID,
    data_len_range = c.CKR_DATA_LEN_RANGE,
    device_error = c.CKR_DEVICE_ERROR,
    device_memory = c.CKR_DEVICE_MEMORY,
    device_removed = c.CKR_DEVICE_REMOVED,
    encrypted_data_invalid = c.CKR_ENCRYPTED_DATA_INVALID,
    encrypted_data_len_range = c.CKR_ENCRYPTED_DATA_LEN_RANGE,
    function_canceled = c.CKR_FUNCTION_CANCELED,
    function_not_parallel = c.CKR_FUNCTION_NOT_PARALLEL,
    function_not_supported = c.CKR_FUNCTION_NOT_SUPPORTED,
    key_handle_invalid = c.CKR_KEY_HANDLE_INVALID,
    key_size_range = c.CKR_KEY_SIZE_RANGE,
    key_type_inconsistent = c.CKR_KEY_TYPE_INCONSISTENT,
    key_not_needed = c.CKR_KEY_NOT_NEEDED,
    key_changed = c.CKR_KEY_CHANGED,
    key_needed = c.CKR_KEY_NEEDED,
    key_indigestible = c.CKR_KEY_INDIGESTIBLE,
    key_function_not_permitted = c.CKR_KEY_FUNCTION_NOT_PERMITTED,
    key_not_wrappable = c.CKR_KEY_NOT_WRAPPABLE,
    key_unextractable = c.CKR_KEY_UNEXTRACTABLE,
    mechanism_invalid = c.CKR_MECHANISM_INVALID,
    mechanism_param_invalid = c.CKR_MECHANISM_PARAM_INVALID,
    object_handle_invalid = c.CKR_OBJECT_HANDLE_INVALID,
    operation_active = c.CKR_OPERATION_ACTIVE,
    operation_not_initialized = c.CKR_OPERATION_NOT_INITIALIZED,
    pin_incorrect = c.CKR_PIN_INCORRECT,
    pin_invalid = c.CKR_PIN_INVALID,
    pin_len_range = c.CKR_PIN_LEN_RANGE,
    pin_expired = c.CKR_PIN_EXPIRED,
    pin_locked = c.CKR_PIN_LOCKED,
    session_closed = c.CKR_SESSION_CLOSED,
    session_count = c.CKR_SESSION_COUNT,
    session_handle_invalid = c.CKR_SESSION_HANDLE_INVALID,
    session_parallel_not_supported = c.CKR_SESSION_PARALLEL_NOT_SUPPORTED,
    session_read_only = c.CKR_SESSION_READ_ONLY,
    session_exists = c.CKR_SESSION_EXISTS,
    session_read_only_exists = c.CKR_SESSION_READ_ONLY_EXISTS,
    session_read_write_so_exists = c.CKR_SESSION_READ_WRITE_SO_EXISTS,
    signature_invalid = c.CKR_SIGNATURE_INVALID,
    signature_len_range = c.CKR_SIGNATURE_LEN_RANGE,
    template_incomplete = c.CKR_TEMPLATE_INCOMPLETE,
    template_inconsistent = c.CKR_TEMPLATE_INCONSISTENT,
    token_not_present = c.CKR_TOKEN_NOT_PRESENT,
    token_not_recognized = c.CKR_TOKEN_NOT_RECOGNIZED,
    token_write_protected = c.CKR_TOKEN_WRITE_PROTECTED,
    unwrapping_key_handle_invalid = c.CKR_UNWRAPPING_KEY_HANDLE_INVALID,
    unwrapping_key_size_range = c.CKR_UNWRAPPING_KEY_SIZE_RANGE,
    unwrapping_key_type_inconsistent = c.CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT,
    user_already_logged_in = c.CKR_USER_ALREADY_LOGGED_IN,
    user_not_logged_in = c.CKR_USER_NOT_LOGGED_IN,
    user_pin_not_initialized = c.CKR_USER_PIN_NOT_INITIALIZED,
    user_type_invalid = c.CKR_USER_TYPE_INVALID,
    user_another_already_logged_in = c.CKR_USER_ANOTHER_ALREADY_LOGGED_IN,
    user_too_many_types = c.CKR_USER_TOO_MANY_TYPES,
    wrapped_key_invalid = c.CKR_WRAPPED_KEY_INVALID,
    wrapped_key_len_range = c.CKR_WRAPPED_KEY_LEN_RANGE,
    wrapping_key_handle_invalid = c.CKR_WRAPPING_KEY_HANDLE_INVALID,
    wrapping_key_size_range = c.CKR_WRAPPING_KEY_SIZE_RANGE,
    wrapping_key_type_inconsistent = c.CKR_WRAPPING_KEY_TYPE_INCONSISTENT,
    random_seed_not_supported = c.CKR_RANDOM_SEED_NOT_SUPPORTED,
    random_no_rng = c.CKR_RANDOM_NO_RNG,
    domain_params_invalid = c.CKR_DOMAIN_PARAMS_INVALID,
    curve_not_supported = c.CKR_CURVE_NOT_SUPPORTED,
    buffer_too_small = c.CKR_BUFFER_TOO_SMALL,
    saved_state_invalid = c.CKR_SAVED_STATE_INVALID,
    information_sensitive = c.CKR_INFORMATION_SENSITIVE,
    state_unsaveable = c.CKR_STATE_UNSAVEABLE,
    cryptoki_not_initialized = c.CKR_CRYPTOKI_NOT_INITIALIZED,
    cryptoki_already_initialized = c.CKR_CRYPTOKI_ALREADY_INITIALIZED,
    mutex_bad = c.CKR_MUTEX_BAD,
    mutex_not_locked = c.CKR_MUTEX_NOT_LOCKED,
    new_pin_mode = c.CKR_NEW_PIN_MODE,
    next_otp = c.CKR_NEXT_OTP,
    exceeded_max_iterations = c.CKR_EXCEEDED_MAX_ITERATIONS,
    fips_self_test_failed = c.CKR_FIPS_SELF_TEST_FAILED,
    library_load_failed = c.CKR_LIBRARY_LOAD_FAILED,
    pin_too_weak = c.CKR_PIN_TOO_WEAK,
    public_key_invalid = c.CKR_PUBLIC_KEY_INVALID,
    function_rejected = c.CKR_FUNCTION_REJECTED,

    pub fn toError(self: ReturnValue) Error {
        return switch (self) {
            .cancel => Error.Cancel,
            .host_memory => Error.HostMemory,
            .slot_id_invalid => Error.SlotIdInvalid,
            .general_error => Error.GeneralError,
            .function_failed => Error.FunctionFailed,
            .arguments_bad => Error.ArgumentsBad,
            .no_event => Error.NoEvent,
            .need_to_create_threads => Error.NeedToCreateThreads,
            .cant_lock => Error.CantLock,
            .attribute_read_only => Error.AttributeReadOnly,
            .attribute_sensitive => Error.AttributeSensitive,
            .attribute_type_invalid => Error.AttributeTypeInvalid,
            .attribute_value_invalid => Error.AttributeValueInvalid,
            .action_prohibited => Error.ActionProhibited,
            .data_invalid => Error.DataInvalid,
            .data_len_range => Error.DataLenRange,
            .device_error => Error.DeviceError,
            .device_memory => Error.DeviceMemory,
            .device_removed => Error.DeviceRemoved,
            .encrypted_data_invalid => Error.EncryptedDataInvalid,
            .encrypted_data_len_range => Error.EncryptedDataLenRange,
            .function_canceled => Error.FunctionCancelled,
            .function_not_parallel => Error.FunctionNotParallel,
            .function_not_supported => Error.FunctionNotSupported,
            .key_handle_invalid => Error.KeyHandleInvalid,
            .key_size_range => Error.KeySizeRange,
            .key_type_inconsistent => Error.KeyTypeInconsistent,
            .key_not_needed => Error.KeyNotNeeded,
            .key_changed => Error.KeyChanged,
            .key_needed => Error.KeyNeeded,
            .key_indigestible => Error.KeyIndigestible,
            .key_function_not_permitted => Error.KeyFunctionNotPermitted,
            .key_not_wrappable => Error.KeyNotWrappable,
            .key_unextractable => Error.KeyUnextractable,
            .mechanism_invalid => Error.MechanismInvalid,
            .mechanism_param_invalid => Error.MechanismParamInvalid,
            .object_handle_invalid => Error.ObjectHandleInvalid,
            .operation_active => Error.OperationActive,
            .operation_not_initialized => Error.OperationNotInitialized,
            .pin_incorrect => Error.PINIncorrect,
            .pin_invalid => Error.PINInvalid,
            .pin_len_range => Error.PINLenRange,
            .pin_expired => Error.PINExpired,
            .pin_locked => Error.PINLocked,
            .session_closed => Error.SessionClosed,
            .session_count => Error.SessionCount,
            .session_handle_invalid => Error.SessionHandleInvalid,
            .session_parallel_not_supported => Error.SessionParallelNotSupported,
            .session_read_only => Error.SessionReadOnly,
            .session_exists => Error.SessionExists,
            .session_read_only_exists => Error.SessionReadOnlyExists,
            .session_read_write_so_exists => Error.SessionReadWriteSOExists,
            .signature_invalid => Error.SignatureInvalid,
            .signature_len_range => Error.SignatureLenRange,
            .template_incomplete => Error.TemplateIncomplete,
            .template_inconsistent => Error.TemplateInconsistent,
            .token_not_present => Error.TokenNotPresent,
            .token_not_recognized => Error.TokenNotRecognized,
            .token_write_protected => Error.TokenWriteProhibited,
            .unwrapping_key_handle_invalid => Error.UnwrappingKeyHandleInvalid,
            .unwrapping_key_size_range => Error.UnwrappingKeySizeRange,
            .unwrapping_key_type_inconsistent => Error.UnwrappingKeyTypeInconsistent,
            .user_already_logged_in => Error.UserAlreadyLoggedIn,
            .user_not_logged_in => Error.UserNotLoggedIn,
            .user_pin_not_initialized => Error.UserPINNotInitialized,
            .user_type_invalid => Error.UserTypeInvalid,
            .user_another_already_logged_in => Error.UserAnotherAlreadyLoggedIn,
            .user_too_many_types => Error.UserTooManyTypes,
            .wrapped_key_invalid => Error.WrappedKeyInvalid,
            .wrapped_key_len_range => Error.WrappedKeyLenRange,
            .wrapping_key_handle_invalid => Error.WrappingKeyHandleInvalid,
            .wrapping_key_size_range => Error.WrappingKeySizeRange,
            .wrapping_key_type_inconsistent => Error.WrappingKeyTypeInconsistent,
            .random_seed_not_supported => Error.RandomSeedNotSupported,
            .random_no_rng => Error.RandomNoRNG,
            .domain_params_invalid => Error.DomainParamsInvalid,
            .curve_not_supported => Error.CurveNotSupported,
            .buffer_too_small => Error.BufferTooSmall,
            .saved_state_invalid => Error.SavedStateInvalid,
            .information_sensitive => Error.InformationSensitive,
            .state_unsaveable => Error.StateUnsavable,
            .cryptoki_not_initialized => Error.CryptokiNotInitialized,
            .cryptoki_already_initialized => Error.CryptokiAlreadyInitialized,
            .mutex_bad => Error.MutexBad,
            .mutex_not_locked => Error.MutexNotLocked,
            .new_pin_mode => Error.NewPINMode,
            .next_otp => Error.NextOTP,
            .exceeded_max_iterations => Error.ExceededMaxIterations,
            .fips_self_test_failed => Error.FIPSSelfTestFailed,
            .library_load_failed => Error.LibraryLoadFailed,
            .pin_too_weak => Error.PINTooWeak,
            .public_key_invalid => Error.PublicKeyInvalid,
            .function_rejected => Error.FunctionRejected,
            else => Error.Unknown,
        };
    }
};

fn returnValueToError(rv: ReturnValue) Error {
    return switch (rv) {
        .cancel => Error.Cancel,
        .host_memory => Error.HostMemory,
        .slot_id_invalid => Error.SlotIdInvalid,
        .general_error => Error.GeneralError,
        .function_failed => Error.FunctionFailed,
        .arguments_bad => Error.ArgumentsBad,
        .no_event => Error.NoEvent,
        .need_to_create_threads => Error.NeedToCreateThreads,
        .cant_lock => Error.CantLock,
        .attribute_read_only => Error.AttributeReadOnly,
        .attribute_sensitive => Error.AttributeSensitive,
        .attribute_type_invalid => Error.AttributeTypeInvalid,
        .attribute_value_invalid => Error.AttributeValueInvalid,
        .action_prohibited => Error.ActionProhibited,
        .data_invalid => Error.DataInvalid,
        .data_len_range => Error.DataLenRange,
        .device_error => Error.DeviceError,
        .device_memory => Error.DeviceMemory,
        .device_removed => Error.DeviceRemoved,
        .encrypted_data_invalid => Error.EncryptedDataInvalid,
        .encrypted_data_len_range => Error.EncryptedDataLenRange,
        .function_canceled => Error.FunctionCancelled,
        .function_not_parallel => Error.FunctionNotParallel,
        .function_not_supported => Error.FunctionNotSupported,
        .key_handle_invalid => Error.KeyHandleInvalid,
        .key_size_range => Error.KeySizeRange,
        .key_type_inconsistent => Error.KeyTypeInconsistent,
        .key_not_needed => Error.KeyNotNeeded,
        .key_changed => Error.KeyChanged,
        .key_needed => Error.KeyNeeded,
        .key_indigestible => Error.KeyIndigestible,
        .key_function_not_permitted => Error.KeyFunctionNotPermitted,
        .key_not_wrappable => Error.KeyNotWrappable,
        .key_unextractable => Error.KeyUnextractable,
        .mechanism_invalid => Error.MechanismInvalid,
        .mechanism_param_invalid => Error.MechanismParamInvalid,
        .object_handle_invalid => Error.ObjectHandleInvalid,
        .operation_active => Error.OperationActive,
        .operation_not_initialized => Error.OperationNotInitialized,
        .pin_incorrect => Error.PINIncorrect,
        .pin_invalid => Error.PINInvalid,
        .pin_len_range => Error.PINLenRange,
        .pin_expired => Error.PINExpired,
        .pin_locked => Error.PINLocked,
        .session_closed => Error.SessionClosed,
        .session_count => Error.SessionCount,
        .session_handle_invalid => Error.SessionHandleInvalid,
        .session_parallel_not_supported => Error.SessionParallelNotSupported,
        .session_read_only => Error.SessionReadOnly,
        .session_exists => Error.SessionExists,
        .session_read_only_exists => Error.SessionReadOnlyExists,
        .session_read_write_so_exists => Error.SessionReadWriteSOExists,
        .signature_invalid => Error.SignatureInvalid,
        .signature_len_range => Error.SignatureLenRange,
        .template_incomplete => Error.TemplateIncomplete,
        .template_inconsistent => Error.TemplateInconsistent,
        .token_not_present => Error.TokenNotPresent,
        .token_not_recognized => Error.TokenNotRecognized,
        .token_write_protected => Error.TokenWriteProhibited,
        .unwrapping_key_handle_invalid => Error.UnwrappingKeyHandleInvalid,
        .unwrapping_key_size_range => Error.UnwrappingKeySizeRange,
        .unwrapping_key_type_inconsistent => Error.UnwrappingKeyTypeInconsistent,
        .user_already_logged_in => Error.UserAlreadyLoggedIn,
        .user_not_logged_in => Error.UserNotLoggedIn,
        .user_pin_not_initialized => Error.UserPINNotInitialized,
        .user_type_invalid => Error.UserTypeInvalid,
        .user_another_already_logged_in => Error.UserAnotherAlreadyLoggedIn,
        .user_too_many_types => Error.UserTooManyTypes,
        .wrapped_key_invalid => Error.WrappedKeyInvalid,
        .wrapped_key_len_range => Error.WrappedKeyLenRange,
        .wrapping_key_handle_invalid => Error.WrappingKeyHandleInvalid,
        .wrapping_key_size_range => Error.WrappingKeySizeRange,
        .wrapping_key_type_inconsistent => Error.WrappingKeyTypeInconsistent,
        .random_seed_not_supported => Error.RandomSeedNotSupported,
        .random_no_rng => Error.RandomNoRNG,
        .domain_params_invalid => Error.DomainParamsInvalid,
        .curve_not_supported => Error.CurveNotSupported,
        .buffer_too_small => Error.BufferTooSmall,
        .saved_state_invalid => Error.SavedStateInvalid,
        .information_sensitive => Error.InformationSensitive,
        .state_unsaveable => Error.StateUnsavable,
        .cryptoki_not_initialized => Error.CryptokiNotInitialized,
        .cryptoki_already_initialized => Error.CryptokiAlreadyInitialized,
        .mutex_bad => Error.MutexBad,
        .mutex_not_locked => Error.MutexNotLocked,
        .new_pin_mode => Error.NewPINMode,
        .next_otp => Error.NextOTP,
        .exceeded_max_iterations => Error.ExceededMaxIterations,
        .fips_self_test_failed => Error.FIPSSelfTestFailed,
        .library_load_failed => Error.LibraryLoadFailed,
        .pin_too_weak => Error.PINTooWeak,
        .public_key_invalid => Error.PublicKeyInvalid,
        .function_rejected => Error.FunctionRejected,
        else => Error.Unknown,
    };
}

pub const MechanismType = enum(c_ulong) {
    rsa_pkcs_key_pair_gen = c.CKM_RSA_PKCS_KEY_PAIR_GEN,
    rsa_pkcs = c.CKM_RSA_PKCS,
    rsa_9796 = c.CKM_RSA_9796,
    rsa_x509 = c.CKM_RSA_X_509,
    md2_rsa_pkcs = c.CKM_MD2_RSA_PKCS,
    md5_rsa_pkcs = c.CKM_MD5_RSA_PKCS,
    sha1_rsa_pkcs = c.CKM_SHA1_RSA_PKCS,
    ripemd128_rsa_pkcs = c.CKM_RIPEMD128_RSA_PKCS,
    ripemd160_rsa_pkcs = c.CKM_RIPEMD160_RSA_PKCS,
    rsa_pkcs_oaep = c.CKM_RSA_PKCS_OAEP,
    rsa_x9_31_key_pair_gen = c.CKM_RSA_X9_31_KEY_PAIR_GEN,
    rsa_x9_31 = c.CKM_RSA_X9_31,
    sha1_rsa_x9_31 = c.CKM_SHA1_RSA_X9_31,
    rsa_pkcs_pss = c.CKM_RSA_PKCS_PSS,
    sha1_rsa_pkcs_pss = c.CKM_SHA1_RSA_PKCS_PSS,
    dsa_key_pair_gen = c.CKM_DSA_KEY_PAIR_GEN,
    dsa = c.CKM_DSA,
    dsa_sha1 = c.CKM_DSA_SHA1,
    dsa_sha224 = c.CKM_DSA_SHA224,
    dsa_sha256 = c.CKM_DSA_SHA256,
    dsa_sha384 = c.CKM_DSA_SHA384,
    dsa_sha512 = c.CKM_DSA_SHA512,
    dh_pkcs_key_pair_gen = c.CKM_DH_PKCS_KEY_PAIR_GEN,
    dh_pkcs_derive = c.CKM_DH_PKCS_DERIVE,
    x9_42_dh_key_pair_gen = c.CKM_X9_42_DH_KEY_PAIR_GEN,
    x9_42_dh_derive = c.CKM_X9_42_DH_DERIVE,
    x9_42_dh_hybrid_derive = c.CKM_X9_42_DH_HYBRID_DERIVE,
    x9_42_mqv_derive = c.CKM_X9_42_MQV_DERIVE,
    sha256_rsa_pkcs = c.CKM_SHA256_RSA_PKCS,
    sha384_rsa_pkcs = c.CKM_SHA384_RSA_PKCS,
    sha512_rsa_pkcs = c.CKM_SHA512_RSA_PKCS,
    sha256_rsa_pkcs_pss = c.CKM_SHA256_RSA_PKCS_PSS,
    sha384_rsa_pkcs_pss = c.CKM_SHA384_RSA_PKCS_PSS,
    sha512_rsa_pkcs_pss = c.CKM_SHA512_RSA_PKCS_PSS,
    sha224_rsa_pkcs = c.CKM_SHA224_RSA_PKCS,
    sha224_rsa_pkcs_pss = c.CKM_SHA224_RSA_PKCS_PSS,
    sha512_224 = c.CKM_SHA512_224,
    sha512_224_hmac = c.CKM_SHA512_224_HMAC,
    sha512_224_hmac_general = c.CKM_SHA512_224_HMAC_GENERAL,
    sha512_224_key_derivation = c.CKM_SHA512_224_KEY_DERIVATION,
    sha512_256 = c.CKM_SHA512_256,
    sha512_256_hmac = c.CKM_SHA512_256_HMAC,
    sha512_256_hmac_general = c.CKM_SHA512_256_HMAC_GENERAL,
    sha512_256_key_derivation = c.CKM_SHA512_256_KEY_DERIVATION,
    sha512_t = c.CKM_SHA512_T,
    sha512_t_hmac = c.CKM_SHA512_T_HMAC,
    sha512_t_hmac_general = c.CKM_SHA512_T_HMAC_GENERAL,
    sha512_t_key_derivation = c.CKM_SHA512_T_KEY_DERIVATION,
    rc2_key_gen = c.CKM_RC2_KEY_GEN,
    rc2_ecb = c.CKM_RC2_ECB,
    rc2_cbc = c.CKM_RC2_CBC,
    rc2_mac = c.CKM_RC2_MAC,
    rc2_mac_general = c.CKM_RC2_MAC_GENERAL,
    rc2_cbc_pad = c.CKM_RC2_CBC_PAD,
    rc4_key_gen = c.CKM_RC4_KEY_GEN,
    rc4 = c.CKM_RC4,
    des_key_gen = c.CKM_DES_KEY_GEN,
    des_ecb = c.CKM_DES_ECB,
    des_cbc = c.CKM_DES_CBC,
    des_mac = c.CKM_DES_MAC,
    des_mac_general = c.CKM_DES_MAC_GENERAL,
    des_cbc_pad = c.CKM_DES_CBC_PAD,
    des2_key_gen = c.CKM_DES2_KEY_GEN,
    des3_key_gen = c.CKM_DES3_KEY_GEN,
    des3_ecb = c.CKM_DES3_ECB,
    des3_cbc = c.CKM_DES3_CBC,
    des3_mac = c.CKM_DES3_MAC,
    des3_mac_general = c.CKM_DES3_MAC_GENERAL,
    des3_cbc_pad = c.CKM_DES3_CBC_PAD,
    des3_cmac_general = c.CKM_DES3_CMAC_GENERAL,
    des3_cmac = c.CKM_DES3_CMAC,
    cdmf_key_gen = c.CKM_CDMF_KEY_GEN,
    cdmf_ecb = c.CKM_CDMF_ECB,
    cdmf_cbc = c.CKM_CDMF_CBC,
    cdmf_mac = c.CKM_CDMF_MAC,
    cdmf_mac_general = c.CKM_CDMF_MAC_GENERAL,
    cdmf_cbc_pad = c.CKM_CDMF_CBC_PAD,
    des_ofb64 = c.CKM_DES_OFB64,
    des_ofb8 = c.CKM_DES_OFB8,
    des_cfb64 = c.CKM_DES_CFB64,
    des_cfb8 = c.CKM_DES_CFB8,
    md2 = c.CKM_MD2,
    md2_hmac = c.CKM_MD2_HMAC,
    md2_hmac_general = c.CKM_MD2_HMAC_GENERAL,
    md5 = c.CKM_MD5,
    md5_hmac = c.CKM_MD5_HMAC,
    md5_hmac_general = c.CKM_MD5_HMAC_GENERAL,
    sha_1 = c.CKM_SHA_1,
    sha_1_hmac = c.CKM_SHA_1_HMAC,
    sha_1_hmac_general = c.CKM_SHA_1_HMAC_GENERAL,
    ripemd128 = c.CKM_RIPEMD128,
    ripemd128_hmac = c.CKM_RIPEMD128_HMAC,
    ripemd128_hmac_general = c.CKM_RIPEMD128_HMAC_GENERAL,
    ripemd160 = c.CKM_RIPEMD160,
    ripemd160_hmac = c.CKM_RIPEMD160_HMAC,
    ripemd160_hmac_general = c.CKM_RIPEMD160_HMAC_GENERAL,
    sha256 = c.CKM_SHA256,
    sha256_hmac = c.CKM_SHA256_HMAC,
    sha256_hmac_general = c.CKM_SHA256_HMAC_GENERAL,
    sha224 = c.CKM_SHA224,
    sha224_hmac = c.CKM_SHA224_HMAC,
    sha224_hmac_general = c.CKM_SHA224_HMAC_GENERAL,
    sha384 = c.CKM_SHA384,
    sha384_hmac = c.CKM_SHA384_HMAC,
    sha384_hmac_general = c.CKM_SHA384_HMAC_GENERAL,
    sha512 = c.CKM_SHA512,
    sha512_hmac = c.CKM_SHA512_HMAC,
    sha512_hmac_general = c.CKM_SHA512_HMAC_GENERAL,
    securid_key_gen = c.CKM_SECURID_KEY_GEN,
    securid = c.CKM_SECURID,
    hotp_key_gen = c.CKM_HOTP_KEY_GEN,
    hotp = c.CKM_HOTP,
    acti = c.CKM_ACTI,
    acti_key_gen = c.CKM_ACTI_KEY_GEN,
    cast_key_gen = c.CKM_CAST_KEY_GEN,
    cast_ecb = c.CKM_CAST_ECB,
    cast_cbc = c.CKM_CAST_CBC,
    cast_mac = c.CKM_CAST_MAC,
    cast_mac_general = c.CKM_CAST_MAC_GENERAL,
    cast_cbc_pad = c.CKM_CAST_CBC_PAD,
    cast3_key_gen = c.CKM_CAST3_KEY_GEN,
    cast3_ecb = c.CKM_CAST3_ECB,
    cast3_cbc = c.CKM_CAST3_CBC,
    cast3_mac = c.CKM_CAST3_MAC,
    cast3_mac_general = c.CKM_CAST3_MAC_GENERAL,
    cast3_cbc_pad = c.CKM_CAST3_CBC_PAD,
    // CAST5 mechanisms omitted intentionally, since CAST-128 is the same thing.
    cast128_key_gen = c.CKM_CAST128_KEY_GEN,
    cast128_ecb = c.CKM_CAST128_ECB,
    cast128_cbc = c.CKM_CAST128_CBC,
    cast128_mac = c.CKM_CAST128_MAC,
    cast128_mac_general = c.CKM_CAST128_MAC_GENERAL,
    cast128_cbc_pad = c.CKM_CAST128_CBC_PAD,
    rc5_key_gen = c.CKM_RC5_KEY_GEN,
    rc5_ecb = c.CKM_RC5_ECB,
    rc5_cbc = c.CKM_RC5_CBC,
    rc5_mac = c.CKM_RC5_MAC,
    rc5_mac_general = c.CKM_RC5_MAC_GENERAL,
    rc5_cbc_pad = c.CKM_RC5_CBC_PAD,
    idea_key_gen = c.CKM_IDEA_KEY_GEN,
    idea_ecb = c.CKM_IDEA_ECB,
    idea_cbc = c.CKM_IDEA_CBC,
    idea_mac = c.CKM_IDEA_MAC,
    idea_mac_general = c.CKM_IDEA_MAC_GENERAL,
    idea_cbc_pad = c.CKM_IDEA_CBC_PAD,
    generic_secret_key_gen = c.CKM_GENERIC_SECRET_KEY_GEN,
    concatenate_base_and_key = c.CKM_CONCATENATE_BASE_AND_KEY,
    concatenate_base_and_data = c.CKM_CONCATENATE_BASE_AND_DATA,
    concatenate_data_and_base = c.CKM_CONCATENATE_DATA_AND_BASE,
    xor_base_and_data = c.CKM_XOR_BASE_AND_DATA,
    extract_key_from_key = c.CKM_EXTRACT_KEY_FROM_KEY,
    ssl3_pre_master_key_gen = c.CKM_SSL3_PRE_MASTER_KEY_GEN,
    ssl3_master_key_derive = c.CKM_SSL3_MASTER_KEY_DERIVE,
    ssl3_key_and_mac_derive = c.CKM_SSL3_KEY_AND_MAC_DERIVE,
    ssl3_master_key_derive_dh = c.CKM_SSL3_MASTER_KEY_DERIVE_DH,
    tls_pre_master_key_gen = c.CKM_TLS_PRE_MASTER_KEY_GEN,
    tls_master_key_derive = c.CKM_TLS_MASTER_KEY_DERIVE,
    tls_key_and_mac_derive = c.CKM_TLS_KEY_AND_MAC_DERIVE,
    tls_master_key_derive_dh = c.CKM_TLS_MASTER_KEY_DERIVE_DH,
    tls_prf = c.CKM_TLS_PRF,
    ssl3_md5_mac = c.CKM_SSL3_MD5_MAC,
    ssl3_sha1_mac = c.CKM_SSL3_SHA1_MAC,
    md5_key_derivation = c.CKM_MD5_KEY_DERIVATION,
    md2_key_derivation = c.CKM_MD2_KEY_DERIVATION,
    sha1_key_derivation = c.CKM_SHA1_KEY_DERIVATION,
    sha256_key_derivation = c.CKM_SHA256_KEY_DERIVATION,
    sha384_key_derivation = c.CKM_SHA384_KEY_DERIVATION,
    sha512_key_derivation = c.CKM_SHA512_KEY_DERIVATION,
    sha224_key_derivation = c.CKM_SHA224_KEY_DERIVATION,
    pbe_md2_des_cbc = c.CKM_PBE_MD2_DES_CBC,
    pbe_md5_des_cbc = c.CKM_PBE_MD5_DES_CBC,
    pbe_md5_cast_cbc = c.CKM_PBE_MD5_CAST_CBC,
    pbe_md5_cast3_cbc = c.CKM_PBE_MD5_CAST3_CBC,
    // CAST5 mechanisms omitted intentionally, since CAST-128 is the same thing.
    pbe_md5_cast128_cbc = c.CKM_PBE_MD5_CAST128_CBC,
    pbe_sha1_cast128_cbc = c.CKM_PBE_SHA1_CAST128_CBC,
    pbe_sha1_rc4_128 = c.CKM_PBE_SHA1_RC4_128,
    pbe_sha1_rc4_40 = c.CKM_PBE_SHA1_RC4_40,
    pbe_sha1_des3_ede_cbc = c.CKM_PBE_SHA1_DES3_EDE_CBC,
    pbe_sha1_des2_ede_cbc = c.CKM_PBE_SHA1_DES2_EDE_CBC,
    pbe_sha1_rc2_128_cbc = c.CKM_PBE_SHA1_RC2_128_CBC,
    pbe_sha1_rc2_40_cbc = c.CKM_PBE_SHA1_RC2_40_CBC,
    pkcs5_pbkd2 = c.CKM_PKCS5_PBKD2,
    pba_sha1_with_sha1_hmac = c.CKM_PBA_SHA1_WITH_SHA1_HMAC,
    wtls_pre_master_key_gen = c.CKM_WTLS_PRE_MASTER_KEY_GEN,
    wtls_master_key_derive = c.CKM_WTLS_MASTER_KEY_DERIVE,
    wtls_master_key_derive_dh_ecc = c.CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC,
    wtls_prf = c.CKM_WTLS_PRF,
    wtls_server_key_and_mac_derive = c.CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE,
    wtls_client_key_and_mac_derive = c.CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE,
    tls10_mac_server = c.CKM_TLS10_MAC_SERVER,
    tls10_mac_client = c.CKM_TLS10_MAC_CLIENT,
    tls12_mac = c.CKM_TLS12_MAC,
    tls12_kdf = c.CKM_TLS12_KDF,
    tls12_master_key_derive = c.CKM_TLS12_MASTER_KEY_DERIVE,
    tls12_key_and_mac_derive = c.CKM_TLS12_KEY_AND_MAC_DERIVE,
    tls12_master_key_derive_dh = c.CKM_TLS12_MASTER_KEY_DERIVE_DH,
    tls12_key_safe_derive = c.CKM_TLS12_KEY_SAFE_DERIVE,
    tls_mac = c.CKM_TLS_MAC,
    tls_kdf = c.CKM_TLS_KDF,
    key_wrap_lynks = c.CKM_KEY_WRAP_LYNKS,
    key_wrap_set_oaep = c.CKM_KEY_WRAP_SET_OAEP,
    cms_sig = c.CKM_CMS_SIG,
    kip_derive = c.CKM_KIP_DERIVE,
    kip_wrap = c.CKM_KIP_WRAP,
    kip_mac = c.CKM_KIP_MAC,
    camellia_key_gen = c.CKM_CAMELLIA_KEY_GEN,
    camellia_ecb = c.CKM_CAMELLIA_ECB,
    camellia_cbc = c.CKM_CAMELLIA_CBC,
    camellia_mac = c.CKM_CAMELLIA_MAC,
    camellia_mac_general = c.CKM_CAMELLIA_MAC_GENERAL,
    camellia_cbc_pad = c.CKM_CAMELLIA_CBC_PAD,
    camellia_ecb_encrypt_data = c.CKM_CAMELLIA_ECB_ENCRYPT_DATA,
    camellia_cbc_encrypt_data = c.CKM_CAMELLIA_CBC_ENCRYPT_DATA,
    camellia_ctr = c.CKM_CAMELLIA_CTR,
    aria_key_gen = c.CKM_ARIA_KEY_GEN,
    aria_ecb = c.CKM_ARIA_ECB,
    aria_cbc = c.CKM_ARIA_CBC,
    aria_mac = c.CKM_ARIA_MAC,
    aria_mac_general = c.CKM_ARIA_MAC_GENERAL,
    aria_cbc_pad = c.CKM_ARIA_CBC_PAD,
    aria_ecb_encrypt_data = c.CKM_ARIA_ECB_ENCRYPT_DATA,
    aria_cbc_encrypt_data = c.CKM_ARIA_CBC_ENCRYPT_DATA,
    seed_key_gen = c.CKM_SEED_KEY_GEN,
    seed_ecb = c.CKM_SEED_ECB,
    seed_cbc = c.CKM_SEED_CBC,
    seed_mac = c.CKM_SEED_MAC,
    seed_mac_general = c.CKM_SEED_MAC_GENERAL,
    seed_cbc_pad = c.CKM_SEED_CBC_PAD,
    seed_ecb_encrypt_data = c.CKM_SEED_ECB_ENCRYPT_DATA,
    seed_cbc_encrypt_data = c.CKM_SEED_CBC_ENCRYPT_DATA,
    skipjack_key_gen = c.CKM_SKIPJACK_KEY_GEN,
    skipjack_ecb64 = c.CKM_SKIPJACK_ECB64,
    skipjack_cbc64 = c.CKM_SKIPJACK_CBC64,
    skipjack_ofb64 = c.CKM_SKIPJACK_OFB64,
    skipjack_cfb64 = c.CKM_SKIPJACK_CFB64,
    skipjack_cfb32 = c.CKM_SKIPJACK_CFB32,
    skipjack_cfb16 = c.CKM_SKIPJACK_CFB16,
    skipjack_cfb8 = c.CKM_SKIPJACK_CFB8,
    skipjack_wrap = c.CKM_SKIPJACK_WRAP,
    skipjack_private_wrap = c.CKM_SKIPJACK_PRIVATE_WRAP,
    skipjack_relayx = c.CKM_SKIPJACK_RELAYX,
    kea_key_pair_gen = c.CKM_KEA_KEY_PAIR_GEN,
    kea_key_derive = c.CKM_KEA_KEY_DERIVE,
    kea_derive = c.CKM_KEA_DERIVE,
    fortezza_timestamp = c.CKM_FORTEZZA_TIMESTAMP,
    baton_key_gen = c.CKM_BATON_KEY_GEN,
    baton_ecb128 = c.CKM_BATON_ECB128,
    baton_ecb96 = c.CKM_BATON_ECB96,
    baton_cbc128 = c.CKM_BATON_CBC128,
    baton_counter = c.CKM_BATON_COUNTER,
    baton_shuffle = c.CKM_BATON_SHUFFLE,
    baton_wrap = c.CKM_BATON_WRAP,
    // ommited ecdsa_key_pair_gen (deprecated name conflicts with ec_key_pair_gen)
    ec_key_pair_gen = c.CKM_EC_KEY_PAIR_GEN,
    ecdsa = c.CKM_ECDSA,
    ecdsa_sha1 = c.CKM_ECDSA_SHA1,
    ecdsa_sha224 = c.CKM_ECDSA_SHA224,
    ecdsa_sha256 = c.CKM_ECDSA_SHA256,
    ecdsa_sha384 = c.CKM_ECDSA_SHA384,
    ecdsa_sha512 = c.CKM_ECDSA_SHA512,
    ecdh1_derive = c.CKM_ECDH1_DERIVE,
    ecdh1_cofactor_derive = c.CKM_ECDH1_COFACTOR_DERIVE,
    ecmqv_derive = c.CKM_ECMQV_DERIVE,
    ecdh_aes_key_wrap = c.CKM_ECDH_AES_KEY_WRAP,
    rsa_aes_key_wrap = c.CKM_RSA_AES_KEY_WRAP,
    juniper_key_gen = c.CKM_JUNIPER_KEY_GEN,
    juniper_ecb128 = c.CKM_JUNIPER_ECB128,
    juniper_cbc128 = c.CKM_JUNIPER_CBC128,
    juniper_counter = c.CKM_JUNIPER_COUNTER,
    juniper_shuffle = c.CKM_JUNIPER_SHUFFLE,
    juniper_wrap = c.CKM_JUNIPER_WRAP,
    fasthash = c.CKM_FASTHASH,
    aes_key_gen = c.CKM_AES_KEY_GEN,
    aes_ecb = c.CKM_AES_ECB,
    aes_cbc = c.CKM_AES_CBC,
    aes_mac = c.CKM_AES_MAC,
    aes_mac_general = c.CKM_AES_MAC_GENERAL,
    aes_cbc_pad = c.CKM_AES_CBC_PAD,
    aes_ctr = c.CKM_AES_CTR,
    aes_gcm = c.CKM_AES_GCM,
    aes_ccm = c.CKM_AES_CCM,
    aes_cts = c.CKM_AES_CTS,
    aes_cmac = c.CKM_AES_CMAC,
    aes_cmac_general = c.CKM_AES_CMAC_GENERAL,
    aes_xcbc_mac = c.CKM_AES_XCBC_MAC,
    aes_xcbc_mac_96 = c.CKM_AES_XCBC_MAC_96,
    aes_gmac = c.CKM_AES_GMAC,
    blowfish_key_gen = c.CKM_BLOWFISH_KEY_GEN,
    blowfish_cbc = c.CKM_BLOWFISH_CBC,
    twofish_key_gen = c.CKM_TWOFISH_KEY_GEN,
    twofish_cbc = c.CKM_TWOFISH_CBC,
    blowfish_cbc_pad = c.CKM_BLOWFISH_CBC_PAD,
    twofish_cbc_pad = c.CKM_TWOFISH_CBC_PAD,
    des_ecb_encrypt_data = c.CKM_DES_ECB_ENCRYPT_DATA,
    des_cbc_encrypt_data = c.CKM_DES_CBC_ENCRYPT_DATA,
    des3_ecb_encrypt_data = c.CKM_DES3_ECB_ENCRYPT_DATA,
    des3_cbc_encrypt_data = c.CKM_DES3_CBC_ENCRYPT_DATA,
    aes_ecb_encrypt_data = c.CKM_AES_ECB_ENCRYPT_DATA,
    aes_cbc_encrypt_data = c.CKM_AES_CBC_ENCRYPT_DATA,
    gostr3410_key_pair_gen = c.CKM_GOSTR3410_KEY_PAIR_GEN,
    gostr3410 = c.CKM_GOSTR3410,
    gostr3410_with_gostr3411 = c.CKM_GOSTR3410_WITH_GOSTR3411,
    gostr3410_key_wrap = c.CKM_GOSTR3410_KEY_WRAP,
    gostr3410_derive = c.CKM_GOSTR3410_DERIVE,
    gostr3411 = c.CKM_GOSTR3411,
    gostr3411_hmac = c.CKM_GOSTR3411_HMAC,
    gost28147_key_gen = c.CKM_GOST28147_KEY_GEN,
    gost28147_ecb = c.CKM_GOST28147_ECB,
    gost28147 = c.CKM_GOST28147,
    gost28147_mac = c.CKM_GOST28147_MAC,
    gost28147_key_wrap = c.CKM_GOST28147_KEY_WRAP,
    dsa_parameter_gen = c.CKM_DSA_PARAMETER_GEN,
    dh_pkcs_parameter_gen = c.CKM_DH_PKCS_PARAMETER_GEN,
    x9_42_dh_parameter_gen = c.CKM_X9_42_DH_PARAMETER_GEN,
    dsa_probablistic_parameter_gen = c.CKM_DSA_PROBABLISTIC_PARAMETER_GEN,
    dsa_shawe_taylor_parameter_gen = c.CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN,
    aes_ofb = c.CKM_AES_OFB,
    aes_cfb64 = c.CKM_AES_CFB64,
    aes_cfb8 = c.CKM_AES_CFB8,
    aes_cfb128 = c.CKM_AES_CFB128,
    aes_cfb1 = c.CKM_AES_CFB1,
    aes_key_wrap = c.CKM_AES_KEY_WRAP,
    aes_key_wrap_pad = c.CKM_AES_KEY_WRAP_PAD,
    rsa_pkcs_tpm_1_1 = c.CKM_RSA_PKCS_TPM_1_1,
    rsa_pkcs_oaep_tpm_1_1 = c.CKM_RSA_PKCS_OAEP_TPM_1_1,
    // Some implementations of PKCS#11 back-ported v3 mechanisms to v2.40.... so we do the same to avoid panics.
    ec_edwards_key_pair_gen = 0x00001055,
    eddsa = 0x00001057,
};

pub const UserType = enum(c_ulong) {
    system_operator = c.CKU_SO,
    user = c.CKU_USER,
    context_specific = c.CKU_CONTEXT_SPECIFIC,
};
